---
version: 2
plan:
  project-key: DEMONSTRATION
  key: NEWDEMONSTRATION
  name: key demonstration
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!'
