---
version: 2
plan:
  project-key: DEMONSTRATIONKEYS
  key: NEWDEMONSTRATIONKEYS
  name: key demonstration
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!'
