---
version: 2
plan:
  project-key: DEMONSTRATIONKEYSDEMO
  key: NEWDEMONSTRATIONKEYDEMO
  name: key demonstration
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script:
      - echo 'Hello World!' 
